[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
source = "apps/api"
